### ISSUE TITLE
Any New Phone Number is accepted when changing a user's contact info

### ISSUE THREAD

**Issue by mchan948** [HTBox/crisischeckin#392] opened 2015-10-01 19:00 UTC
1) Create an account
2) Login as the newly created account
3) Click on link for Change Contact Info
4) Enter "11" for New Phone Number field

Expected Result: Validation error message thrown specifying that this is not a legitimate phone number
Actual Result: Information saved successfully

**Comment by TravCav** [comment] 2015-11-13 21:01
Not sure we should limit the input on this.  What are the requirements for "legitimate" phone number?  Depending on the environment that's been setup 11 may be a valid extension.

**Comment by TravCav** [comment] 2015-11-16 14:09
duplicate of #293

**Comment by BillWagner** [comment] 2015-11-17 03:29
Closing as duplicate of #293

**Closed by BillWagner** 2015-11-17 03:29 UTC
