### ISSUE TITLE
Black block covers the screen under Firefox

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#190] opened 2014-06-25 14:51 UTC
Under Firefox, I log in as Administrator. I click on "View Volunteers". I see a black box appearing under the drop-down box. I switch to this window to log this bug. I return to the Firefox window to try to reproduce the problem. I click on Home (Disaster List) and then on "View Volunteers" again. The black box effect does not reproduce; nor does it reproduce when I log in again. I do see effects like this intermittently throughout the application, however. There is a BB Test Assistant log to show if it's needed.

I've attached a screen shot of a similar problem I observed at one point, when, as an Administrator, I tried to volunteer for a disaster.
![blackboxdropdown](https://cloud.githubusercontent.com/assets/4061222/3386862/2c3eba62-fc78-11e3-98c1-c9b89363c0fa.png)
![volunteerfordisaster](https://cloud.githubusercontent.com/assets/4061222/3386863/2c44a3b4-fc78-11e3-8616-2c9e29f231a1.png)

**Comment by BillWagner** [comment] 2015-08-08 17:22
closing as Can't reproduce. I've tried several times, and it has not re-appeared

**Closed by BillWagner** 2015-08-08 17:22 UTC
