### ISSUE TITLE
Error while registering user

### ISSUE THREAD

**Issue by hari** [HTBox/crisischeckin#514] opened 2016-05-04 13:45 UTC
Priority - P1
Steps to create
1. Register new user
2. give the user id as "hari@'
3. Got the message as "User id already exists"
4. If you go ahead registering the user  without changing it . it gives the following error
![screenshot 2016-05-04 at 9 41 44 am](https://cloud.githubusercontent.com/assets/19173572/15015981/f0c163b4-11dc-11e6-9c53-734706af9d5d.png)

**Comment by aarjay** [comment] 2016-05-04 15:06
Milestone - Features backlog

**Comment by adinnaplus** [comment] 2016-05-04 15:20
Hi. This is a duplicate of #512

**Comment by mjmilan** [comment] 2016-05-04 22:50
Implementing the above pull request resolves this issue.

**Closed** 2016-05-05 17:17 UTC
