### ISSUE TITLE
Register : No length validation on fields

### ISSUE THREAD

**Issue by drosskopf** [HTBox/crisischeckin#59] opened 2013-10-02 17:36 UTC
You need to limit the lenght of data in the fields to ensure the data quality.  Otherwise you might have this issue. 

![crisis1](https://f.cloud.github.com/assets/5590134/1255699/2795302e-2b89-11e3-8a53-3b7517802835.jpg)

**Comment by tditiecher** [comment] 2015-03-10 20:38
@BillWagner Who can/should specify the max length of all text input fields in the application so that we can solve this issue?

**Comment by BillWagner** [comment] 2015-03-11 02:09
Right now, I think we should specify reasonable maximum limits. 

The problem is that a malicious user can register and enter very long strings for input and make a complete mess of the displays for others.

I'd recommend a couple items:  

1. We should limit the length at the database to a very large maximum (like, say, 512 characters for the name and such).
2. We should sanitize the display logic to a more reasonable screen length. (like, say 80 chars for the name).

Thoughts?

**Comment by camjbakke** [comment] 2015-04-25 02:32
I am willing to work on this one. 

I agree if we don't have a clear requirement, we can do something we think is reasonable and always change the value later if needed. For now I will just add some data annotations for the length constrains on the view models and models. I will leave the DB alone for now. Based on the initial migration, it looks like all of the strings are the default length of nvarchar(max).

I am thinking that I will update both the view models and the Models (on the context) with the length constraints.

Should I go through all of the models, or just the registration related ones due to the scope of the bug being for "Register : No length validation on fields"?

**Comment by BillWagner** [comment] 2015-04-27 15:50
@camjbakke It's yours.  

I agree that updating the models and view models with reasonable length constraints would be best. 

I think it would be smart to look at all the models and make sure there are 'reasonable' lengths. The bug manifests itself when someone enters very, very long strings of data and the display becomes unreadable.

**Comment by BillWagner** [comment] 2015-08-08 17:51
Tidying up: didn't close this issue when I merged #285.

**Closed by BillWagner** 2015-08-08 17:51 UTC
Labels: bug
