### ISSUE TITLE
enhancement suggestion: choose cluster later

### ISSUE THREAD

**Issue by DotGraham** [HTBox/crisischeckin#101] opened 2013-10-03 22:20 UTC
When you first sign up, you have to choose a cluster, but there is no information about what the clusters are. Why not let people sign up first and then choose a relevant cluster when they know what to choose. This would also give you the opportunity to highlight which clusters are most in need of volunteers.

**Comment by tditiecher** [comment] 2015-02-19 14:12
@BillWagner Is this issue still relevant?

**Comment by BillWagner** [comment] 2015-02-19 14:34
Thanks for reminder. I will close this as by design: volunteers will always know their cluster when registering, and will never* change it.

* Well, almost never. But close enough to never that we won't add this feature.

**Closed by BillWagner** 2015-02-19 14:34 UTC
Labels: enhancement
