### ISSUE TITLE
Adding New Cluster: Entry of an extended name causes an exception error (See Below)

### ISSUE THREAD

**Issue by wferrarini** [HTBox/crisischeckin#357] opened 2015-10-01 12:29 UTC
Steps to Reproduce

Open Crisis Checkin
From the main menu select Cluster List
Below the list of clusters label select Create New 

Enter the FOllowing String

This is my cluster creation 23434242#&()%&)*$_l;f;aj               ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa  ldjfafjsa;f fjl;af jl; fj;f ja;f asfsdfsa

Click the Create Button

Notice the behavior stated:

![image](https://cloud.githubusercontent.com/assets/4839738/10220553/75c4252c-6816-11e5-8726-60221bd77e0f.png)

**Comment by jsucupira** [comment] 2015-10-01 12:40
I think this is a duplicate issue.  The first issue reporting this error was issue #350

**Comment by wferrarini** [comment] 2015-10-01 12:45
Thank you yes I apologize for not looking at the existing issues before I opened this one, it appears you can't use special characters or exceed a certain limit in the field :)
I am at work and I thought I would give it a look. Now back to testing my product :)

 


     On Thursday, October 1, 2015 8:40 AM, Jonathas Sucupira <notifications@github.com> wrote:
   

 I think this is a duplicate issue. The first issue reporting this error was issue #350—

**Comment by wadewachs** [comment] 2015-10-01 15:32
wferrarini - Thanks for participating as part of the Virtual conference (or so I assume). We really appreciate it.

**Comment by wferrarini** [comment] 2015-10-01 16:05
Hi Wade you are welcome, if I had more time I would test it longer but I have to do my own work lol
 


     On Thursday, October 1, 2015 11:32 AM, wadewachs <notifications@github.com> wrote:
   

 wferrarini - Thanks for participating as part of the Virtual conference (or so I assume). We really appreciate it.—

**Comment by TravCav** [comment] 2016-01-05 13:52
@BillWagner this is indeed a duplicate of #350 and can be closed. It seems to have been fixed at some point and is now displaying the appropriate validation message.

**Comment by BillWagner** [comment] 2016-01-05 13:57
Closing as a duplicate of #350

**Closed by BillWagner** 2016-01-05 13:57 UTC
