### ISSUE TITLE
Url after error in volunteering form is unstable, cannot be refreshed/loaded.

### ISSUE THREAD

**Issue by dennisjbell** [HTBox/crisischeckin#19] opened 2013-10-02 00:17 UTC
As a standard user, after you try to submit a volunteer form with malformed data, you are directed to the following page that displays the errors:
https://crisischeckin.azurewebsites.net/Home/Assets

However, if you hit enter on the address bar to refresh without resubmitting the data,  the page cannot be loaded (probably due to missing post data), and presents the following error:

Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

Requested URL: /Home/Assign

**Comment by tditiecher** [comment] 2015-02-23 19:38
In case of 404 errors we could redirect to a custom 404 page or maybe just redirect to /Home.

In general a custom 404 with the same look and feel as the rest of the site might not be a bad idea, it's better than looking at a ASP.NET server error.

In this specific case the user already was visiting the home page so the page after reload is the same page as he came from and therefore the least disruptive.

What is the desired behaviour?

**Comment by BillWagner** [comment] 2015-02-24 16:33
I'd like to have a custom 404 page. That would alert users that they either typed the URL wrong, or we have a link with an incorrect href. (Going to the home page would be ambiguous as to the cause).

**Comment by TravCav** [comment] 2015-11-16 14:14
Original issue cannot be reproduced.  Or is this now a ticket to make a custom 404 page?

**Comment by BillWagner** [comment] 2015-11-17 03:29
Verified as fixed. Closing.

**Closed by BillWagner** 2015-11-17 03:29 UTC
Labels: bug
