### ISSUE TITLE
System.NullReferenceException if Assigned Coordinator for activity is removed from volunteering

### ISSUE THREAD

**Issue by MichaelH3** [HTBox/crisischeckin#406] opened 2015-10-01 20:43 UTC
If an assigned coordinator stops volunteering for a disaster and activity (removes their self from volunteers) and the Admin tries to access the Cluster Coordinators for that disaster, an error is thrown by the server.

Steps to reproduce:
Have a user volunteering for a disaster and activity/cluster
As Admin, assign that volunteer as the cluster coordinator
As the volunteer, remove that disaster and activity/cluster from the list of events you're volunteering for
As Admin, try to access the Cluster Coordinators for that disaster

Expected: 
The volunteer is no longer listed as the cluster coordinator

Actual:
The System.NullReferenceException is thrown. If the volunteer re-volunteers for the same event at the same time, the Admin will be able to access that cluster coordinators

Looks like issue could be the same as #355

**Comment by mjmilan** [comment] 2016-01-06 15:16
Looking at the code for this, the issue is in the ClusterCoordinatorController/GetDisasterClusterCoordinatorsViewModel method. As the code tries to build the clusterViewModel it tries to assign to the Coordinators property. That attempt involves the following invocation of the Select LinQ method:

.Select(x => new ClusterCoordinatorViewModel
                                                          {
                                                              Name = x.Person.FullName,
                                                              Id = x.Id,
                                                          })

The issue is that should there be a cluster which does not have a clusterCoordinators record matching it, then a null value is passed into the Select... 

The specific issue could be resolved by generating the Coordinators list before trying to instantiate the ClusterViewModel, thereby giving us the control to be able to simply pass an empty list should there be no Coordinators for the selected cluster.

That just gets us past the immediate problem though - there could be issues further down the line with the UI code... I'll take a look at it and see what happens...

A word of caution - I am new to htbox...

**Comment by rwherrmann** [comment] 2016-01-06 15:16
@rwherrmann will work on this issue.

**Comment by mjmilan** [comment] 2016-01-06 15:17
@rwherrmann - note my comment above as to cause...

**Comment by rwherrmann** [comment] 2016-01-06 15:19
@rwherrmann will work on this one.

**Comment by mjmilan** [comment] 2016-01-06 15:19
Actually, a slightly different approach is needed...

**Comment by mjmilan** [comment] 2016-01-06 15:21
You have it

**Comment by mjmilan** [comment] 2016-01-06 15:36
My comments above were misleading - a ClusterCoordinator is found, but the Person property hasn't been populated - hence the call to Person.FullName on the Select lambda fails...

Sorry for confusion...

**Comment by rwherrmann** [comment] 2016-01-06 15:45
Thanks for the info.  I am thinking that the source of the issue is that
when a volunteer removes themselves from a commitment, we should also check
if they are a coordinator and remove that as well.  We can code around the
issue in the ClusterCoordinator controller but the underlying data issue
will still be there.

Does that make sense?

**Comment by mjmilan** [comment] 2016-01-06 16:05
Yes - you're on the right track... I've kept looking at this, and it looks like the DataService's RemoveCommitmentById method needs to also remove any ClusterCoordinators for the Cluster we are looking at.

I'll leave that for you, unless you can't do it, in which case I will do it later tonight...

**Comment by rwherrmann** [comment] 2016-01-06 16:07
That's what I am thinking too - remove the cluster coordinator data at that
point if it exists.  I can finish that now.

**Comment by mjmilan** [comment] 2016-01-06 16:07
It goes without saying (and indeed just did) that the only ClusterCoordinators we would remove would be where the cluster and person matched the cluster and person of the commitment we were removing though...

ClusterId is nullable on the Commitment by the looks of things as well...

**Comment by mjmilan** [comment] 2016-01-06 16:10
It would be nice to do this at the schema level. I'm not seriously proposing a trigger, but that sort of idea - so if the commitment is removed, the clusterCoordinator dies with it as a consequence of the database alone. There could be an approach with ForeignKeys, but I'm too tired to think about it...

My advice then - go for the hack on the data service...

**Comment by BillWagner** [comment] 2016-01-06 19:47
Fixed in PR #457

**Closed by BillWagner** 2016-01-06 19:47 UTC
Labels: jump-in
